site_name: MkLorum
hljs_style: github
hljs_languages:
    - css
    - html
nav:
    - Home: index.md
    - About: about.md
    - HTML5基础: 001-basic-html-and-html5.md
    - CSS基础: 002-basic-css.md

theme: readthedocs
